enemy_color: "blue"
# enemy_color: "blue"


#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: CPU
min_confidence: 0.8
use_traditional: false

#####-----ROI-----#####
roi: 
  x: 420
  y: 150
  width: 700
  height: 700

use_roi: false

#####-----工业相机参数-----#####
# camera_name: "mindvision"
# exposure_ms: 8
# gamma: 0.6
# vid_pid: "f622:d132"

camera_name: "hikrobot"
exposure_ms: 13
gain: 10
vid_pid: "2bdf:0001"

#####-----USB相机参数-----#####
image_width: 640
image_height: 360
new_image_width: 1280
new_image_height: 720
fov_h: 87.7
fov_v: 56.7 
new_fov_h: 67
new_fov_v: 40.9
usb_frame_rate: 100
usb_exposure: 315 #1-80000______250
usb_gamma: 160
usb_gain: 10 #0-96


#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
min_confidence: 0.8

#####-----cboard参数-----#####
quaternion_canid: 0x411
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"

com_port: "/dev/serial_vision"

#####-----tracker参数-----###
min_detect_count: 5
max_temp_lost_count: 15
outpost_max_temp_lost_count: 150

#####-----aimer参数-----#####
yaw_offset: 2 # degree -2.5 注意下面全是角度
pitch_offset: 2 # degree 2
comming_angle: 70 # degree
leaving_angle: 20 # degree
min_spin_speed: 2 # rad/s
decision_speed: 12 # rad/s
high_speed_delay_time: 0.048 # s
low_speed_delay_time: 0.048 # s

#####-----decider参数-----#####
mode: 2

#####-----shooter参数-----#####
first_tolerance: 2 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 3 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

#####-----工业相机标定参数-----#####
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# 哨兵参数
# 重投影误差: 0.0358px
camera_matrix: [1740.0427777774178, 0, 717.47607276266672, 0, 1740.0367769542684, 562.82245147301683, 0, 0, 1]
distort_coeffs: [-0.076906154927112932, 0.091331239621293844, 0.00010176702573307289, -0.00040075019976923627, 0]

# 相机同理想情况的偏角: yaw-0.12 pitch-0.67 roll1.16 degree
# 标定板到世界坐标系原点的水平距离: 1.90 m
# 标定板同竖直摆放时的偏角: yaw-95.54 pitch19.05 roll-0.45 degree
R_camera2gimbal: [0.0019162517313319949, -0.011719563215539231, 0.99992948742265764, -0.99979262931637336, 0.020249976473315556, 0.0021533270729344194, -0.020273784648038341, -0.99972625767800394, -0.011678328869226999]
t_camera2gimbal: [0.11927399952677062, -0.00049749372519933982, 0.038734712788162075]


# 相机同理想情况的偏角: yaw0.33 pitch1.08 roll-0.63 degree
# 标定板到世界坐标系原点的水平距离: 1.61 m
# 标定板同竖直摆放时的偏角: yaw8.67 pitch27.16 roll-3.57 degree
# R_camera2gimbal: [-0.0060467523836795272, 0.018744605548249197, 0.99980601946000069, -0.9999213697182161, -0.011097562920299193, -0.005839390214414545, 0.010985953142839783, -0.99976271377765991, 0.018810235869674365]
# t_camera2gimbal: [0.066812917468701868, -0.0012313939243398372, -0.057165553847480073]
#####-----buff_detector参数-----#####
model: "assets/yolo11_buff_int8.xml"

#####-----buff_aimer参数-----#####
fire_gap_time: 0.600   # s
predict_time: 0.090     # s
